export {default as AlertSquareSVG} from './alert-square.svg';
export {default as AlertTriangleSVG} from './alert-triangle.svg';
export {default as AlertCircleSVG} from './alert-circle.svg';
export {default as Attachment01SVG} from './attachment-01.svg';
export {default as Attachment02SVG} from './attachment-02.svg';
export {default as ArrowCircleUpLeftSVG} from './arrow-circle-up-left.svg';
export {default as ArrowNarrowLeftSVG} from './arrow-narrow-left.svg';
export {default as ArrowNarrowRightSVG} from './arrow-narrow-right.svg';
export {default as ArrowLeftSVG} from './arrow-left.svg';
export {default as ArrowRightSVG} from './arrow-right.svg';
export {default as ArrowSquareUpRightSVG} from './arrow-square-up-right.svg';
export {default as BarChart07SVG} from './bar-chart-07.svg';
export {default as BarChart10SVG} from './bar-chart-10.svg';
export {default as BankNote01SVG} from './bank-note-01.svg';
export {default as BookmarkAddSVG} from './bookmark-add.svg';
export {default as BookClosedSVG} from './book-closed.svg';
export {default as BookOpen01SVG} from './book-open-01.svg';
export {default as Briefcase02SVG} from './briefcase-02.svg';
export {default as Building07SVG} from './building-07.svg';
export {default as CalendarPlus02SVG} from './calendar-plus-02.svg';
export {default as CalendarSVG} from './calendar.svg';
export {default as ChatMessageChecked01SVG} from './chat-message-checked-01.svg'
export {default as ChatMessageChecked02SVG} from './chat-message-checked-02.svg'
export {default as CheckSVG} from './check.svg';
export {default as ChevronDownSVG} from './chevron-down.svg';
export {default as ChevronLeftSVG} from './chevron-left.svg';
export {default as ChevronRightSVG} from './chevron-right.svg';
export {default as CheckVerified02SVG} from './check-verified-02.svg';
export {default as ChevronUpSVG} from './chevron-up.svg';
export {default as ClockCheckSVG} from './clock-check.svg';
export {default as CLockSVG} from './clock.svg';
export {default as Copy06SVG} from './copy-06.svg';
export {default as Dataflow01SVG} from './dataflow-01.svg';
export {default as Download01SVG} from './download_01.svg';
export {default as DotsVerticalSVG} from './dots-vertical.svg';
export {default as DotsGridSVG} from './dots-grid.svg';
export {default as Edit03SVG} from './edit-03.svg';
export {default as Edit04SVG} from './edit-04.svg';
export {default as FaceSmileSVG} from './face-smile.svg';
export {default as File04SVG} from './file-04.svg';
export {default as File06SVG} from './file-06.svg';
export {default as FileAttachment04SVG} from './file-attachment-04.svg';
export {default as Image02SVG} from './image-02.svg';
export {default as LayoutCalendarSVG} from './layout-calendar.svg';
export {default as LayoutLeftSVG} from './layout-left.svg';
export {default as LayoutGrid02SVG} from './layout-grid-02.svg';
export {default as Link01SVG} from './link-01.svg';
export {default as Login01SVG} from './log-in-01.svg';
export {default as Logout01SVG} from './log-out-01.svg';
export {default as Lock01SVG} from './lock-01.svg';
export {default as MarkerPin02SVG} from './marker-pin-02.svg';
export {default as MessageNotificationCircleSVG} from './message-notification-circle.svg';
export {default as MessageTextSquare01SVG} from './message-text-square-01.svg';
export {default as MessageTextSquare02SVG} from './message-text-square-02.svg';
export {default as MinusSVG} from './minus.svg';
export {default as MusicNote01SVG} from './music-note-01.svg';
export {default as PackageSVG} from './package.svg';
export {default as PauseCircleSVG} from './pause-circle.svg';
export {default as Pencil01SVG} from './pencil-01.svg';
export {default as PlayButtonSVG} from './play-button.svg';
export {default as PlaySVG} from './play.svg';
export {default as PlusSVG} from './plus.svg';
export {default as Rss01SVG} from './rss-01.svg';
export {default as Rows03SVG} from './rows-03.svg';
export {default as Save01SVG} from './save-01.svg';
export {default as SearchSmSVG} from './search-sm.svg';
export {default as SearchMdSVG} from './search-md.svg';
export {default as SearchLgSVG} from './search-lg.svg';
export {default as Settings01SVG} from './settings-01.svg';
export {default as Settings02SVG} from './settings-02.svg';
export {default as Settings04SVG} from './settings-04.svg';
export {default as SupportSVG} from './support.svg';
export {default as SlashOctagonSVG} from './slash-octagon.svg';
export {default as SlashCircleSVG} from './slash-circle-02.svg';
export {default as SwitchHorizontal02SVG} from './switch-horizontal-02.svg';
export {default as Trash01SVG} from './trash-01.svg';
export {default as Trash03SVG} from './trash-03.svg';
export {default as Type02SVG} from './type-02.svg';
export {default as Upload01SVG} from './upload-01.svg';
export {default as User01SVG} from './user-01.svg';
export {default as UserEditSVG} from './user-edit.svg';
export {default as UsersEditSVG} from './users-edit.svg'
export {default as Users01SVG} from './users-01.svg';
export {default as Users02SVG} from './users-02.svg';
export {default as UserPlus01} from './user-plus-01.svg'
export {default as VerifiedSVG} from './verified.svg';
export {default as VolumeMaxSVG} from './volume-max.svg';
export {default as VolumeXSVG} from './volume-x.svg';
export {default as Wallet03SVG} from './wallet-03.svg';
export {default as XCloseSVG} from './x-close.svg';
export {default as EyeSVG} from './eye.svg';
export {default as MessageSquare02SVG} from './message-square-02.svg';
export {default as ShareArrowSVG} from './share-arrow.svg';
export {default as ThumbsUpSVG} from './thumbs-up.svg';
export {default as LayoutAlt01SVG} from './layout-alt-01.svg';
export {default as LayoutAlt03SVG} from './layout-alt-03.svg';
export {default as CircleSVG} from './circle.svg';
export {default as CalendarCheck01SVG} from './calendar-check-01.svg';
export {default as Dotpoints01SVG} from './dotpoints-01.svg';
export {default as BookmarkCheckSVG} from './bookmark-check.svg';
export {default as Star01SVG} from './star-01.svg';
export {default as Bell01SVG} from './bell-01.svg';
export {default as BellPlusSVG} from './bell-plus.svg';
export {default as BookmarkSVG} from './bookmark.svg';
export {default as FlashSVG} from './flash.svg';
export {default as FilterLinesSVG} from './filter-lines.svg';
export {default as MagicWandSVG} from './magic-wand-02.svg'
export {default as RepeatSVG} from './repeat-02.svg'
export {default as Repeat04SVG} from './repeat-04.svg'
export {default as FileQuestion02SVG} from './file-question-02.svg';
export {default as SwitchHorizontal01SVG} from './switch-horizontal-01.svg';
export {default as Coins04SVG} from './coins-04.svg';
export {default as MessageNotificationSquareSVG} from './message-notification-square.svg';
export {default as Menu01SVG} from './menu-01.svg';
export {default as InfoCircleSVG} from './info-circle.svg';
export {default as CornerDownRightSVG} from './corner-down-right.svg';
export {default as DotsRowSVG} from "./dots-row.svg"
export {default as MapPointSVG} from "./map-point.svg"
export {default as DotsColumnSVG} from "./dots-column.svg"
export {default as UnverifiedSVG} from "./unverified.svg"
export {default as PhoneSVG} from "./phone.svg"
export {default as Mail01SVG} from "./mail-01.svg"
export {default as PasscodeLockSVG} from "./passcode-lock.svg"
export {default as CornerUpLeftSVG} from "./corner-up-left.svg"
export {default as Send03SVG} from "./send-03.svg"
export {default as SlashCircle01} from "./slash-circle-01.svg"
export {default as LogoSVG} from './Logo.svg'
export {default as Atom01SVG} from './atom-01.svg'
export {default as Glasses02SVG} from './glasses-02.svg'
export {default as CompassSVG} from './compass.svg'
export {default as Link02SVG} from './link-02.svg'
export {default as GraduationHat01SVG} from './graduation-hat-01.svg'