export const LIMIT_SEARCH_PARAM_NAME = 'limit'
export const SKIP_SEARCH_PARAM_NAME = 'skip'
export const PAGINATION_STEP = 25
export const SKIP_SEARCH_PARAM_DEFAULT = 0
export const LIMIT_SEARCH_PARAM_DEFAULT = PAGINATION_STEP + SKIP_SEARCH_PARAM_DEFAULT